schedules:
  - cron: "0 7 * * 1"
    displayName: Mon_12AM
    branches:
      include:
        - main

trigger: none

jobs:
  - job: "ROCM_Benchmarking_FP32"
    timeoutInMinutes: 540

    pool: LinuxAMDGPUPool

    steps:
      - bash: |
          sudo sysctl -w kernel.core_pattern="$(Build.SourcesDirectory)/build/core-%e-%s-%u-%g-%p-%t.dump"
          ulimit -c unlimited
          python -m pip install -U pip
          python -m pip install -r $(Build.SourcesDirectory)/requirements.txt
          python -m pip install -r $(Build.SourcesDirectory)/tools/benchmarkers/requirements.txt
          echo "mkdir $HOME/.ccache"
          mkdir $HOME/.ccache
          echo "ln -s $HOME/.ccache $(System.DefaultWorkingDirectory)/ccache"
          ln -s $HOME/.ccache $(System.DefaultWorkingDirectory)/ccache
          conan remote add accera $(CONAN_REMOTE)
          conan user -p $(CONAN_PWD) -r accera $(CONAN_USERNAME)
        displayName: Install prereqs
        env:
          CONAN_PWD: $(CONAN_PWD)

      - bash: |
          git submodule init
          git submodule update
          ./external/vcpkg/bootstrap-vcpkg.sh
          ./external/vcpkg/vcpkg install catch2 tomlplusplus
        displayName: Update vcpkg dependencies
        workingDirectory: "$(Build.SourcesDirectory)"

      - bash: |
          python ./setup.py build -g -b build -t build bdist_wheel -d build/dist
        displayName: Python build
        workingDirectory: "$(Build.SourcesDirectory)"

      - bash: |
          export PYTHONPATH=$(Build.SourcesDirectory)/build/lib.linux-x86_64-3.8
          export LD_LIBRARY_PATH=${ROCM_PATH}/lib
          echo "LD_LIBRARY_PATH" ${LD_LIBRARY_PATH}
          python gpu_benchmark_tool.py --input gemm_small_MI100.csv,gemm_small.csv --type s --target 'AMD MI100' --branch $(Build.SourceBranch) --output $(Build.SourcesDirectory)/build/lib.linux-x86_64-3.8/accera_benchmarks/results --upload official_build_container_DO_NOT_UPLOAD_HERE --janitor True --verbose True --check True
        displayName: Run fp32 benchmarks MI100
        workingDirectory: "$(Build.SourcesDirectory)/tools/benchmarkers"
        env:
          ACCOUNT_KEY: $(ACCOUNT_KEY)
