schedules:
  - cron: "0 5 * * SUN"
    displayName: Weekly build
    branches:
      include:
        - main

trigger:
  tags:
    include:
    - "v*"

resources:
  pipelines:
  - pipeline: manylinux-llvm
    source: Manylinux LLVM Docker Build
    trigger: true

pool:
  vmImage: 'ubuntu-latest'

strategy:
  matrix:
    Python37:
      Python.Version: "3.7"
      Python.Path: "/opt/python/cp37-cp37m/bin/python3.7"
    Python38:
      Python.Version: "3.8"
      Python.Path: "/opt/python/cp38-cp38/bin/python3.8"
    Python39:
      Python.Version: "3.9"
      Python.Path: "/opt/python/cp39-cp39/bin/python3.9"
    Python310:
      Python.Version: "3.10"
      Python.Path: "/opt/python/cp310-cp310/bin/python3.10"

container:
  image: $(CONTAINER_REGISTRY)/accera-llvm-manylinux2014:$(CONTAINER_TAG)
  endpoint: acceracontainers

steps:
- script: sh .azure/manylinux/build.sh $(Python.Path)
  displayName: Build
  workingDirectory: "$(Build.SourcesDirectory)/"

- script: |
    $(Python.Path) -m pip install dist/wheelhouse/accera-*.whl --find-links=dist/wheelhouse --no-index
    $(Python.Path) -m pip install dist/wheelhouse/accera_gpu-*.whl
    $(Python.Path) -m accera.test.smoke_test
  displayName: Smoke test
  workingDirectory: "$(Build.SourcesDirectory)/"

- task: CopyFiles@2
  condition: always()
  inputs:
    SourceFolder: "$(Build.SourcesDirectory)/dist/wheelhouse"
    Contents: |
      **/*.whl
    TargetFolder: "$(Build.StagingDirectory)/python"
    CleanTargetFolder: true
    OverWrite: true
    preserveTimestamp: true

- task: PublishPipelineArtifact@1
  condition: always()
  inputs:
    targetPath: "$(Build.StagingDirectory)"
    artifact: "Artifacts.$(Python.Version)"
    publishLocation: "pipeline"

- script: $(Python.Path) -m pip install twine keyring artifacts-keyring
  displayName: Install twine

- task: TwineAuthenticate@1
  inputs:
    artifactFeed: 'Accera'

- script: '$(Python.Path) -m twine upload -r Accera --config-file $(PYPIRC_PATH) $(Build.SourcesDirectory)/dist/wheelhouse/*.whl --verbose --skip-existing'
  displayName: Upload the whls to Azure artifacts feed

- task: TwineAuthenticate@1
  inputs:
    pythonUploadServiceConnection: $(PYPI_SERVICE_CONNECTION)
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/v'))

- script: '$(Python.Path) -m twine upload -r $(PYPI_SERVICE_CONNECTION) --config-file $(PYPIRC_PATH) $(Build.SourcesDirectory)/dist/wheelhouse/*.whl --verbose --skip-existing'
  displayName: Upload the whls to PyPI
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/v'))