trigger: none

pool:
  vmImage: "macos-11"

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: "3.9" # TODO: switch to 3.10 once onnxruntime is released for it
      addToPath: true
      architecture: "x64"

  - bash: |
      brew install ccache ninja conan libomp
      python -m pip install -U pip
      python -m pip install -r $(Build.SourcesDirectory)/requirements.txt
      conan remote add accera $(CONAN_REMOTE)
      conan user -p $(CONAN_PWD) -r accera $(CONAN_USERNAME)
      mkdir $HOME/.ccache
      ln -s $HOME/.ccache $(System.DefaultWorkingDirectory)/ccache
    displayName: Install prereqs for macOS
    continueOnError: false
    condition: eq( variables['Agent.OS'], 'Darwin' )
    env:
      CONAN_PWD: $(CONAN_PWD)

  - bash: |
      git submodule init
      git submodule update
      ./external/vcpkg/bootstrap-vcpkg.sh
      ./external/vcpkg/vcpkg install catch2 tomlplusplus
    displayName: Update vcpkg dependencies
    workingDirectory: "$(Build.SourcesDirectory)"

  - task: CMake@1
    displayName: CMake configure on macOS
    continueOnError: false
    inputs:
      cmakeArgs: ".. -DCMAKE_BUILD_TYPE=RelWithDebInfo -DLLVM_LIT_ARGS=-vv -GNinja -DLLVM_SETUP_VARIANT=$(LLVM_SETUP_VARIANT)"
    condition: eq( variables['Agent.OS'], 'Darwin' )

  - task: CMake@1
    displayName: CMake default build
    continueOnError: false
    inputs:
      cmakeArgs: "--build . --config RelWithDebInfo"

  - task: CMake@1
    displayName: CMake build check-all
    inputs:
      cmakeArgs: "--build . --config RelWithDebInfo  --target check-all"

  - task: CMake@1
    displayName: CMake install build
    inputs:
      cmakeArgs: "--build . --config RelWithDebInfo --target install"

  - task: PythonScript@0
    displayName: python ./setup.py build -g -b build -t build bdist_wheel -d build/dist
    inputs:
      scriptSource: "filePath"
      scriptPath: "$(Build.SourcesDirectory)/setup.py"
      arguments: "build -g -b build -t build bdist_wheel -d build/dist"
      workingDirectory: "$(Build.SourcesDirectory)/"

  - bash: |
        python -m pip install -r $(Build.SourcesDirectory)/accera/onnx-emitter/test/requirements.txt
        ctest -C RelWithDebInfo -T test -VV -LE benchmark
    displayName: Run all ctest targets
    continueOnError: false
    workingDirectory: "$(Build.SourcesDirectory)/build"
    condition: eq( variables['Agent.OS'], 'Darwin' )

  - task: CopyFiles@2
    condition: always()
    inputs:
      SourceFolder: "$(Build.SourcesDirectory)/build"
      Contents: |
        **/*.mlir
      TargetFolder: "$(Build.StagingDirectory)"
      CleanTargetFolder: true
      OverWrite: true
      preserveTimestamp: true

  - task: PublishPipelineArtifact@1
    condition: always()
    inputs:
      targetPath: "$(Build.StagingDirectory)"
      artifact: "Artifacts"
      publishLocation: "pipeline"

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'CTest'
      testResultsFiles: "**/Test*.xml"
      searchFolder: '$(Build.SourcesDirectory)/build'
