trigger: none

pool:
  vmImage: "macos-12"

variables:
 - name: PIP_CACHE_DIR
   value: $(Pipeline.Workspace)/.pip
 - name: VCPKG_BINARY_SOURCES
   value: "clear;nuget,$(VCPKG_NUGET_FEED),readwrite"

steps:
  - task: NuGetAuthenticate@0

  - task: UsePythonVersion@0
    inputs:
      versionSpec: "3.9" # TODO: switch to 3.10 once onnxruntime is released for it
      addToPath: true
      architecture: "x64"

  - task: Cache@2
    inputs:
      key: 'pip | "$(Agent.OS)" | $(Build.SourcesDirectory)/requirements.txt | $(Build.SourcesDirectory)/accera/onnx-emitter/test/requirements.txt'
      restoreKeys: |
        pip | "$(Agent.OS)"
      path: $(PIP_CACHE_DIR)
    displayName: Cache pip

  - bash: |
      brew install ccache ninja conan libomp
      python -m pip install -U pip
      python -m pip install -r $(Build.SourcesDirectory)/requirements.txt
      conan remote add accera $(CONAN_REMOTE)
      conan user -p $(CONAN_PWD) -r accera $(CONAN_USERNAME)
      echo "##vso[task.prependpath]/usr/lib/ccache"
    displayName: Install prereqs for macOS
    continueOnError: false
    env:
      CONAN_PWD: $(CONAN_PWD)

  - bash: |
      git submodule init
      git submodule update
      ./external/vcpkg/bootstrap-vcpkg.sh
      ./external/vcpkg/vcpkg install catch2 tomlplusplus
    displayName: Update vcpkg dependencies
    workingDirectory: "$(Build.SourcesDirectory)"

  - task: CMake@1
    displayName: CMake configure on macOS
    continueOnError: false
    inputs:
      cmakeArgs: ".. -DCMAKE_BUILD_TYPE=Release -GNinja -DLLVM_SETUP_VARIANT=$(LLVM_SETUP_VARIANT)"

  - task: CMake@1
    displayName: CMake default build
    continueOnError: false
    inputs:
      cmakeArgs: "--build . --config Release --parallel"

  - task: CMake@1
    displayName: CMake build check-all
    inputs:
      cmakeArgs: "--build . --config Release  --target check-all --parallel"

  - task: CMake@1
    displayName: CMake install build
    inputs:
      cmakeArgs: "--build . --config Release --target install --parallel"

  - bash: |
        python -m pip install -r $(Build.SourcesDirectory)/accera/onnx-emitter/test/requirements.txt
        python -m pip install pytest-azurepipelines
        ctest -C Release -T test -VV -LE benchmark --progress
    displayName: Run all ctest targets
    continueOnError: false
    workingDirectory: "$(Build.SourcesDirectory)/build"

  - task: CopyFiles@2
    condition: always()
    inputs:
      SourceFolder: "$(Build.SourcesDirectory)/build"
      Contents: |
        **/*.mlir
      TargetFolder: "$(Build.StagingDirectory)"
      CleanTargetFolder: true
      OverWrite: true
      preserveTimestamp: true

  - task: PublishPipelineArtifact@1
    condition: always()
    inputs:
      targetPath: "$(Build.StagingDirectory)"
      artifact: "Artifacts"
      publishLocation: "pipeline"

  - task: PublishTestResults@2
    condition: always()
    inputs:
      testResultsFormat: 'CTest'
      testResultsFiles: "**/Test*.xml"
      searchFolder: '$(Build.SourcesDirectory)/build'

  - task: PublishTestResults@2
    condition: always()
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: "**/test-*.xml"
      testRunTitle: 'Publish test results for Python'
      searchFolder: '$(Build.SourcesDirectory)/build'
