trigger:
- main

pool:
  vmImage: windows-latest

variables:
  VULKAN_CACHE_DIR: $(Pipeline.Workspace)/.vulkansdk

steps:

- task: UsePythonVersion@0
  inputs:
    versionSpec: "3.9"
    addToPath: true
    architecture: "x64"

- task: PowerShell@2
  displayName: Install prereqs for Windows
  inputs:
    ignoreLASTEXITCODE: true
    errorActionPreference: silentlyContinue
    targetType: "inline"
    script: |
      python -m pip install -U pip
      python -m pip install -r $(Build.SourcesDirectory)/requirements.txt
      conan remote add accera $(CONAN_REMOTE)
      conan user -p $(CONAN_PWD) -r accera $(CONAN_USERNAME)
  continueOnError: false
  condition: eq( variables['Agent.OS'], 'Windows_NT' )
  env:
    CONAN_PWD: $(CONAN_PWD)

  # Begin Vulkan setup tasks
  # The Official Vulkan SDK setup requires elevation to install and cannot be run here. Instead we will build the Vulkan loader.
  # 1. Get the latest SDK version (https://vulkan.lunarg.com/content/view/latest-sdk-version-api)
  # 2. Build the Vulkan loader and headers if not present in the cache (https://github.com/KhronosGroup/Vulkan-Loader/blob/master/BUILD.md)
  # 3. Cache the Vulkan loader and headers using the version file as the hash
- task: PowerShell@2
  displayName: Get Vulkan SDK version
  inputs:
    targetType: "inline"
    script: |
      $SDK_VERSION=(curl https://vulkan.lunarg.com/sdk/latest/windows.txt -UseBasicParsing).Content
      echo Vulkan SDK version: $SDK_VERSION
      echo "##vso[task.setvariable variable=VULKAN_SDK_VERSION]$SDK_VERSION"
      echo $SDK_VERSION > vulkan.version

- task: Cache@2
  displayName: Cache Vulkan SDK
  inputs:
    key: 'vulkan_sdk4 | "$(Agent.OS)" | vulkan.version'
    path: $(VULKAN_CACHE_DIR)
    cacheHitVar: VULKAN_CACHE_RESTORED

- task: PowerShell@2
  displayName: Build Vulkan loader if not cached
  inputs:
    targetType: "inline"
    script: |
      git clone https://github.com/KhronosGroup/Vulkan-Loader.git
      cd Vulkan-Loader
      git checkout tags/sdk-$(VULKAN_SDK_VERSION)
      mkdir build
      cd build
      python ../scripts/update_deps.py
      cmake -C helper.cmake -DCMAKE_INSTALL_PREFIX=$(VULKAN_CACHE_DIR) ..
      cmake --build . --config Release --target install
  continueOnError: false
  condition: ne(variables.VULKAN_CACHE_RESTORED, 'true')

- task: PowerShell@2
  displayName: Copy Vulkan SDK
  inputs:
    targetType: "inline"
    script: Copy-Item $(Build.SourcesDirectory)/Vulkan-Loader/build/Vulkan-Headers/build/install/include -Destination $(VULKAN_CACHE_DIR)/include -Recurse
  continueOnError: false
  condition: ne(variables.VULKAN_CACHE_RESTORED, 'true')

- task: PowerShell@2
  displayName: Setup Vulkan SDK
  inputs:
    targetType: "inline"
    script: |
      echo "##vso[task.setvariable variable=VULKAN_SDK]$(VULKAN_CACHE_DIR)"
      ls $(VULKAN_CACHE_DIR) -Recurse
# End Vulkan setup tasks

- task: PythonScript@0
  displayName: python ./setup.py build -b build -t build bdist_wheel -d build/dist
  inputs:
    scriptSource: "filePath"
    scriptPath: "$(Build.SourcesDirectory)/setup.py"
    arguments: "build -b build -t build bdist_wheel -d build/dist"
    workingDirectory: "$(Build.SourcesDirectory)/"

- task: CopyFiles@2
  condition: always()
  inputs:
    SourceFolder: "$(Build.SourcesDirectory)/build/dist"
    Contents: |
      **/*
    TargetFolder: "$(Build.StagingDirectory)/python"
    CleanTargetFolder: true
    OverWrite: true
    preserveTimestamp: true

- task: BinSkim@4
  inputs:
    InputType: 'Basic'
    Function: 'analyze'
    TargetPattern: 'binskimPattern'
    AnalyzeTargetBinskim: |
      $(Build.SourcesDirectory)\build\*.dll
      $(Build.SourcesDirectory)\build\*.exe
    AnalyzeLocalSymbolDirectories: '$(Build.SourcesDirectory)\build\'
    AnalyzeRecurse: true
    AnalyzeIgnorePdbLoadError: true
    AnalyzeHashes: true
    toolVersion: '1.9.0-prerelease3'
