trigger: none

pool:
  vmImage: "windows-latest"

variables:
 - name: PIP_CACHE_DIR
   value: $(Pipeline.Workspace)/.pip
 - name: VCPKG_BINARY_SOURCES
   value: "clear;nuget,$(VCPKG_NUGET_FEED),readwrite"
 - name: VCPKG_ROOT
   value: "$(Build.SourcesDirectory)/external/vcpkg"

steps:
  - task: NuGetAuthenticate@0

  - task: UsePythonVersion@0
    inputs:
      versionSpec: "3.9" # TODO: switch to 3.10 once onnxruntime is released for it
      addToPath: true
      architecture: "x64"

  - task: Cache@2
    inputs:
      key: 'pip | "$(Agent.OS)" | $(Build.SourcesDirectory)/requirements.txt | $(Build.SourcesDirectory)/accera/onnx-emitter/test/requirements.txt'
      restoreKeys: |
        pip | "$(Agent.OS)"
      path: $(PIP_CACHE_DIR)
    displayName: Cache pip

  - task: PowerShell@2
    displayName: Install prereqs for Windows
    inputs:
      ignoreLASTEXITCODE: true
      errorActionPreference: silentlyContinue
      targetType: "inline"
      script: |
        python -m pip install -U pip
        python -m pip install -r $(Build.SourcesDirectory)/requirements.txt
        conan remote add accera $(CONAN_REMOTE)
        conan user -p $(CONAN_PWD) -r accera $(CONAN_USERNAME)
    continueOnError: false
    env:
      CONAN_PWD: $(CONAN_PWD)

  - script: |
      git submodule init
      git submodule update
      call external\vcpkg\bootstrap-vcpkg.bat
      external\vcpkg\vcpkg.exe install catch2:x64-windows tomlplusplus:x64-windows
    displayName: Update vcpkg dependencies
    workingDirectory: "$(Build.SourcesDirectory)"

  - task: CMake@1
    displayName: CMake configure on Windows
    continueOnError: false
    inputs:
      workingDirectory: 'build\Release'
      cmakeArgs: '..\.. -DCMAKE_BUILD_TYPE=Release -DLLVM_LIT_ARGS=-vv -G"Visual Studio 17 2022" -Ax64 -DLLVM_SETUP_VARIANT=$(LLVM_SETUP_VARIANT)'

  - task: CMake@1
    displayName: CMake default build
    continueOnError: false
    inputs:
      workingDirectory: 'build\Release'
      cmakeArgs: "--build . --config Release"

  - task: CMake@1
    displayName: CMake build check-all
    inputs:
      workingDirectory: 'build\Release'
      cmakeArgs: "--build . --config Release --target check-all"

  - task: CMake@1
    displayName: CMake install build
    inputs:
      workingDirectory: 'build\Release'
      cmakeArgs: "--build . --config Release --target install"

  # Note: windows can result in dll load conflict if --parallel option is used
  - script: |
      call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
      python -m pip install -r $(Build.SourcesDirectory)/accera/onnx-emitter/test/requirements.txt
      python -m pip install pytest-azurepipelines
      ctest -C Release -T test -VV -LE "benchmark" -E "mfma" --progress
    displayName: Run ctest targets with smoke tests
    workingDirectory: "$(Build.SourcesDirectory)/build/Release"

  - task: CopyFiles@2
    condition: always()
    inputs:
      SourceFolder: "$(Build.SourcesDirectory)/build/Release"
      Contents: |
        **/*.mlir
      TargetFolder: "$(Build.StagingDirectory)"
      CleanTargetFolder: true
      OverWrite: true
      preserveTimestamp: true

  - task: PublishPipelineArtifact@1
    condition: always()
    inputs:
      targetPath: "$(Build.StagingDirectory)"
      artifact: "Artifacts"
      publishLocation: "pipeline"

  - task: PublishTestResults@2
    condition: always()
    inputs:
      testResultsFormat: 'CTest'
      testResultsFiles: "**/Test*.xml"
      searchFolder: '$(Build.SourcesDirectory)/build/Release'

  - task: PublishTestResults@2
    condition: always()
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: "**/test-*.xml"
      testRunTitle: 'Publish test results for Python'
      searchFolder: '$(Build.SourcesDirectory)/build'
